### ISSUE TITLE
Operation not permitted: '/tmp/pip-vtUBRD-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.8.0rc1-py2.7.egg-info

### ISSUE THREAD

**Issue by haemi** [mitochrome/complex-gestures-demo#1]
Hi, when running `sudo pip install -r requirements.txt` I get the following stacktrace:

```
  Found existing installation: numpy 1.8.0rc1
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.0rc1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-vtUBRD-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.8.0rc1-py2.7.egg-info'
```

what can I do to solve this? Thanks  a lot for the awesome tutorial!

**Comment by Adam0000** [comment]
Hi haemi. It looks like I forgot to mention activating the virtualenv before installing the pip packages. See https://github.com/mitochrome/complex-gestures-demo/commit/4e908e4dfcf88992cae815f60a27073af4a34f35. Glad you liked the tutorial. :)

**Comment by haemi** [comment]
didn't help, unfortunately :(

**Comment by haemi** [comment]
one step further, but when running the `filter.py`-script I get

```
Traceback (most recent call last):
  File "filter.py", line 11, in <module>
    import protobuf.touches_pb2 as touches_pb2
ImportError: No module named protobuf.touches_pb2
```

**Comment by Adam0000** [comment]
Am I right that you're getting past the `pip install` step now? I noticed you were using `sudo` there, which actually shouldn't be needed.

I have little idea what's causing this import error. With the virtualenv activated (as it should be when running filter.py), could you check what Python version you're using with `python -V`?

It would be helpful if you could clone the project fresh again and copy the terminal commands and output from creating the virtualenv through `pip install` to running filter.py.

**Comment by haemi** [comment]
`pip install` works now, yes.

`python -V` says `2.7.14`

**Comment by Adam0000** [comment]
I have little idea what's causing that error. :( The full terminal log starting at creating the virtualenv might help.

**Comment by haemi** [comment]
this is the terminal log:

```
➜  _AF source venv/bin/activate
(venv) ➜  _AF pip install -r requirements.txt
Collecting click==6.7 (from -r requirements.txt (line 1))
  Using cached click-6.7-py2.py3-none-any.whl
Collecting coremltools==0.5.1 (from -r requirements.txt (line 2))
  Using cached coremltools-0.5.1-py2.7-none-any.whl
Collecting numpy==1.13.0 (from -r requirements.txt (line 3))
  Using cached numpy-1.13.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting protobuf==3.3.0 (from -r requirements.txt (line 4))
Collecting tensorflow==1.2.0 (from -r requirements.txt (line 5))
  Using cached tensorflow-1.2.0-cp27-cp27m-macosx_10_11_x86_64.whl
Collecting six==1.10.0 (from coremltools==0.5.1->-r requirements.txt (line 2))
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./venv/lib/python2.7/site-packages (from protobuf==3.3.0->-r requirements.txt (line 4))
Collecting backports.weakref==1.0rc1 (from tensorflow==1.2.0->-r requirements.txt (line 5))
  Using cached backports.weakref-1.0rc1-py2-none-any.whl
Requirement already satisfied: wheel in ./venv/lib/python2.7/site-packages (from tensorflow==1.2.0->-r requirements.txt (line 5))
Collecting mock>=2.0.0 (from tensorflow==1.2.0->-r requirements.txt (line 5))
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting markdown==2.2.0 (from tensorflow==1.2.0->-r requirements.txt (line 5))
Collecting werkzeug>=0.11.10 (from tensorflow==1.2.0->-r requirements.txt (line 5))
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting html5lib==0.9999999 (from tensorflow==1.2.0->-r requirements.txt (line 5))
Collecting bleach==1.5.0 (from tensorflow==1.2.0->-r requirements.txt (line 5))
  Using cached bleach-1.5.0-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->tensorflow==1.2.0->-r requirements.txt (line 5))
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=2.0.0->tensorflow==1.2.0->-r requirements.txt (line 5))
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Installing collected packages: click, six, numpy, protobuf, coremltools, backports.weakref, funcsigs, pbr, mock, markdown, werkzeug, html5lib, bleach, tensorflow
Successfully installed backports.weakref-1.0rc1 bleach-1.5.0 click-6.7 coremltools-0.5.1 funcsigs-1.0.2 html5lib-0.9999999 markdown-2.2.0 mock-2.0.0 numpy-1.13.0 pbr-3.1.1 protobuf-3.3.0 six-1.10.0 tensorflow-1.2.0 werkzeug-0.12.2
(venv) ➜  _AF python filter.py --test-fraction=0.15 data.trainingset
Traceback (most recent call last):
  File "filter.py", line 11, in <module>
    import protobuf.touches_pb2 as touches_pb2
ImportError: No module named protobuf.touches_pb2
(venv) ➜  _AF
```
